In [1]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
from sklearn.metrics import mean_squared_error
from sklearn import linear_model

# Feature Selection

In [2]:
df = pd.read_csv('data/new_health.csv')
df = df.drop('Unnamed: 0', axis = 1)
df

RELIG_SERVICES_12month  RELIG_IMPORTANT  RELIG_influ_decision  \
0                          0.6         0.333333              0.333333   
1                          0.4         0.666667              0.666667   
2                          0.2         0.333333              0.333333   
3                          0.6         0.000000              0.000000   
4                          0.4         0.000000              0.000000   
...                        ...              ...                   ...   
189290                     0.8         0.000000              0.333333   
189291                     0.4         1.000000              0.333333   
189292                     0.8         0.000000              0.000000   
189293                     0.6         0.333333              0.333333   
189294                     0.6         0.000000              0.000000   

        friend_SHARE_REL  Tabacco_Flag  Alcohol_Flag  Marijunana_Flag  \
0               0.333333           1.0           1.0              1.0   
1               1.000000           1.0           1.0              1.0   
2               0.666667           1.0           1.0              0.0   
3               0.333333           1.0           0.0              0.0   
4               0.333333           1.0           1.0              1.0   
...                  ...           ...           ...              ...   
189290          0.666667           1.0           1.0              0.0   
189291          0.666667           0.0           0.0              0.0   
189292          0.666667           1.0           1.0              1.0   
189293          1.000000           0.0           0.0              0.0   
189294          0.000000           1.0           1.0              1.0   

        Marijuana_Only_Flag  Cocaine_Flag  Crack_Flag  ...  lifetime_mde  \
0                       1.0           0.0         0.0  ...           1.0   
1                       1.0           0.0         0.0  ...           1.0   
2                       0.0           0.0         0.0  ...           0.0   
3                       0.0           0.0         0.0  ...           1.0   
4                       0.0           0.0         0.0  ...           0.0   
...                     ...           ...         ...  ...           ...   
189290                  0.0           0.0         0.0  ...           1.0   
189291                  0.0           0.0         0.0  ...           0.0   
189292                  0.0           1.0         1.0  ...           1.0   
189293                  0.0           0.0         0.0  ...           0.0   
189294                  0.0           0.0         0.0  ...           1.0   

        pst_yr_mde   age  HEALTH  IRSEX   IRMARIT  EDUCCAT2  NEWRACE2  \
0              1.0  0.00    0.00    0.0  0.000000  0.666667  0.000000   
1              1.0  0.00    0.25    1.0  0.333333  0.666667  0.166667   
2              1.0  0.00    0.75    1.0  0.000000  0.000000  0.166667   
3              1.0  0.75    0.75    1.0  0.666667  0.333333  0.166667   
4              1.0  0.00    0.00    1.0  0.000000  0.666667  0.166667   
...            ...   ...     ...    ...       ...       ...       ...   
189290         1.0  0.00    0.00    1.0  0.000000  0.333333  0.166667   
189291         0.0  0.50    0.75    1.0  0.666667  0.333333  0.166667   
189292         1.0  0.50    0.25    0.0  0.333333  1.000000  0.166667   
189293         0.0  0.00    0.00    1.0  0.000000  0.666667  0.166667   
189294         1.0  1.00    0.75    0.0  0.333333  0.000000  0.333333   

        EMPSTATY  suicide_risk  
0       0.000000           0.0  
1       0.000000           0.0  
2       0.333333           0.0  
3       0.666667           0.0  
4       0.333333           0.0  
...          ...           ...  
189290  0.000000           0.0  
189291  0.333333           0.5  
189292  0.000000           0.0  
189293  1.000000           0.0  
189294  0.000000           0.0  

[189295 rows x 43 columns]

In [3]:
df.columns

Index(['RELIG_SERVICES_12month', 'RELIG_IMPORTANT', 'RELIG_influ_decision',
       'friend_SHARE_REL', 'Tabacco_Flag', 'Alcohol_Flag', 'Marijunana_Flag',
       'Marijuana_Only_Flag', 'Cocaine_Flag', 'Crack_Flag', 'Herion_Flag',
       'Hallcinogens_Flag', 'Inhalants_Flag', 'Painkiller_Flag',
       'Tranquilizer_Flag', 'Stimulant Flag', 'Meth_Flag', 'Sedatives Flag',
       'Any_Drug_Flag', 'Drug_Not_Marijunana', 'Ever_Steal_50',
       'Sell_Illegal_Drugs', 'Ever_Booked_Arrested', 'Drug_or_Alc_Past_year',
       'inpatient', 'outpatient', 'needed_not_rcvd', 'rcvd_any_tmt',
       'psych_distress_month', 'psych_distress_yr', 'whodas_score',
       'predicted_ment_ill', 'svrl_days_depressed', 'lifetime_mde',
       'pst_yr_mde', 'age', 'HEALTH', 'IRSEX', 'IRMARIT', 'EDUCCAT2',
       'NEWRACE2', 'EMPSTATY', 'suicide_risk'],
      dtype='object')

In [4]:
df['suicide_risk'].value_counts()

0.000000    178945
0.166667      6795
0.500000      1896
1.000000      1279
0.666667       374
0.333333         6
Name: suicide_risk, dtype: int64

In [5]:
x_data = df.drop(['suicide_risk'],axis=1)
y_data = df['suicide_risk']
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data,test_size=0.2, random_state = 1)

### Approach 1: Ridge Regression

In [6]:
from sklearn.linear_model import Ridge
clf = Ridge().fit(X_train,y_train)
ypred=clf.predict(X_test)

In [7]:
result = mean_squared_error(y_test, ypred)
print('MSE:',result)

MSE: 0.00753706967076093


In [8]:
clf.coef_

array([ 2.84931353e-03,  5.47693970e-03,  2.68161676e-03,  1.14346755e-03,
        1.24333161e-03, -4.99781480e-04, -9.69696588e-04,  3.93511691e-04,
       -7.17422192e-06,  1.01570489e-03, -1.00139956e-03, -7.04184166e-04,
        1.87986738e-03,  1.24867374e-04,  1.17982715e-03, -3.44564098e-03,
        2.56652468e-03,  1.24589174e-04,  9.89301876e-04,  5.95790156e-04,
        6.24775236e-02,  1.57543215e-02, -9.57158862e-04,  1.95931541e-02,
       -1.46466547e-01, -1.01911853e-02, -2.46618350e-02,  6.47828006e-03,
        3.49691043e-02,  1.02915481e-02, -2.70694965e-02,  1.94928318e-01,
       -3.49416330e-01, -7.86531554e-03,  1.34457400e-02, -9.99809853e-03,
        1.47073691e-03, -1.01719166e-03, -5.32843408e-03, -7.33926838e-03,
        2.93306793e-03,  2.70713648e-03])

In [9]:
s = np.sort(abs(clf.coef_))
s

array([7.17422192e-06, 1.24589174e-04, 1.24867374e-04, 3.93511691e-04,
       4.99781480e-04, 5.95790156e-04, 7.04184166e-04, 9.57158862e-04,
       9.69696588e-04, 9.89301876e-04, 1.00139956e-03, 1.01570489e-03,
       1.01719166e-03, 1.14346755e-03, 1.17982715e-03, 1.24333161e-03,
       1.47073691e-03, 1.87986738e-03, 2.56652468e-03, 2.68161676e-03,
       2.70713648e-03, 2.84931353e-03, 2.93306793e-03, 3.44564098e-03,
       5.32843408e-03, 5.47693970e-03, 6.47828006e-03, 7.33926838e-03,
       7.86531554e-03, 9.99809853e-03, 1.01911853e-02, 1.02915481e-02,
       1.34457400e-02, 1.57543215e-02, 1.95931541e-02, 2.46618350e-02,
       2.70694965e-02, 3.49691043e-02, 6.24775236e-02, 1.46466547e-01,
       1.94928318e-01, 3.49416330e-01])

10 most important features:

In [11]:
for i in range(-1, -11, -1):
    print(df.columns[np.where(abs(clf.coef_) == s[i])][0])

svrl_days_depressed
predicted_ment_ill
inpatient
Ever_Steal_50
psych_distress_month
whodas_score
needed_not_rcvd
Drug_or_Alc_Past_year
Sell_Illegal_Drugs
pst_yr_mde


10 least important features:

In [12]:
for i in range(10):
    print(df.columns[np.where(abs(clf.coef_) == s[i])][0])

Cocaine_Flag
Sedatives Flag
Painkiller_Flag
Marijuana_Only_Flag
Alcohol_Flag
Drug_Not_Marijunana
Hallcinogens_Flag
Ever_Booked_Arrested
Marijunana_Flag
Any_Drug_Flag


### Approach 2: LASSO Regression

In [13]:
from sklearn.linear_model import Ridge
clf = linear_model.Lasso(alpha=0.1).fit(X_train,y_train)
ypred=clf.predict(X_test)

In [14]:
result = mean_squared_error(y_test, ypred)
print('MSE:',result)

MSE: 0.010140933911482004


In [15]:
clf.coef_

array([-0.,  0.,  0.,  0.,  0.,  0.,  0., -0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0., -0., -0.,
       -0., -0.,  0.,  0.,  0.,  0., -0., -0., -0., -0.,  0.,  0., -0.,
       -0.,  0.,  0.])

In [16]:
s = np.sort(abs(clf.coef_))
s

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

No features selected according to LASSO.

# Prediction Models

Making suicide risk column categorical:

In [17]:
df['suicide_risk'] = df['suicide_risk']*6
df = df.astype({'suicide_risk':'int'})

In [18]:
df

RELIG_SERVICES_12month  RELIG_IMPORTANT  RELIG_influ_decision  \
0                          0.6         0.333333              0.333333   
1                          0.4         0.666667              0.666667   
2                          0.2         0.333333              0.333333   
3                          0.6         0.000000              0.000000   
4                          0.4         0.000000              0.000000   
...                        ...              ...                   ...   
189290                     0.8         0.000000              0.333333   
189291                     0.4         1.000000              0.333333   
189292                     0.8         0.000000              0.000000   
189293                     0.6         0.333333              0.333333   
189294                     0.6         0.000000              0.000000   

        friend_SHARE_REL  Tabacco_Flag  Alcohol_Flag  Marijunana_Flag  \
0               0.333333           1.0           1.0              1.0   
1               1.000000           1.0           1.0              1.0   
2               0.666667           1.0           1.0              0.0   
3               0.333333           1.0           0.0              0.0   
4               0.333333           1.0           1.0              1.0   
...                  ...           ...           ...              ...   
189290          0.666667           1.0           1.0              0.0   
189291          0.666667           0.0           0.0              0.0   
189292          0.666667           1.0           1.0              1.0   
189293          1.000000           0.0           0.0              0.0   
189294          0.000000           1.0           1.0              1.0   

        Marijuana_Only_Flag  Cocaine_Flag  Crack_Flag  ...  lifetime_mde  \
0                       1.0           0.0         0.0  ...           1.0   
1                       1.0           0.0         0.0  ...           1.0   
2                       0.0           0.0         0.0  ...           0.0   
3                       0.0           0.0         0.0  ...           1.0   
4                       0.0           0.0         0.0  ...           0.0   
...                     ...           ...         ...  ...           ...   
189290                  0.0           0.0         0.0  ...           1.0   
189291                  0.0           0.0         0.0  ...           0.0   
189292                  0.0           1.0         1.0  ...           1.0   
189293                  0.0           0.0         0.0  ...           0.0   
189294                  0.0           0.0         0.0  ...           1.0   

        pst_yr_mde   age  HEALTH  IRSEX   IRMARIT  EDUCCAT2  NEWRACE2  \
0              1.0  0.00    0.00    0.0  0.000000  0.666667  0.000000   
1              1.0  0.00    0.25    1.0  0.333333  0.666667  0.166667   
2              1.0  0.00    0.75    1.0  0.000000  0.000000  0.166667   
3              1.0  0.75    0.75    1.0  0.666667  0.333333  0.166667   
4              1.0  0.00    0.00    1.0  0.000000  0.666667  0.166667   
...            ...   ...     ...    ...       ...       ...       ...   
189290         1.0  0.00    0.00    1.0  0.000000  0.333333  0.166667   
189291         0.0  0.50    0.75    1.0  0.666667  0.333333  0.166667   
189292         1.0  0.50    0.25    0.0  0.333333  1.000000  0.166667   
189293         0.0  0.00    0.00    1.0  0.000000  0.666667  0.166667   
189294         1.0  1.00    0.75    0.0  0.333333  0.000000  0.333333   

        EMPSTATY  suicide_risk  
0       0.000000             0  
1       0.000000             0  
2       0.333333             0  
3       0.666667             0  
4       0.333333             0  
...          ...           ...  
189290  0.000000             0  
189291  0.333333             3  
189292  0.000000             0  
189293  1.000000             0  
189294  0.000000             0  

[189295 rows x 43 columns]

percentage in each category:

In [19]:
df['suicide_risk'].value_counts()/df.shape[0]

0    0.981220
3    0.010016
6    0.006757
4    0.001976
2    0.000032
Name: suicide_risk, dtype: float64

In [20]:
x_data = df.drop(['suicide_risk'],axis=1)
y_data = df['suicide_risk']
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data,test_size=0.2, random_state = 1)

### Approach 1: K-Nearest Neighbors
K-Nearest Neighbors classifies based on proximity to k datapoints.

Note: There is a class imbalance. Since most people fall under the first risk category, K-NN is biased toward predicting that class. While it is good to have high accuracy, in the context of suicide risk, predicting 0 risk is not as important as predicting a risk of 2 or higher. 

Some disadvantages of K-NN observed here: doesn’t learn which features useful, computationally expensive, more noisy features → distance less meaningful

k = 5

In [21]:
knn_clf=KNeighborsClassifier()
knn_clf.fit(X_train,y_train)
ypred=knn_clf.predict(X_test) #These are the predicted output values

In [22]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, ypred)
print('Confusion Matrix:')
print(result)
result1 = classification_report(y_test, ypred)
print('Classification Report:',)
print (result1)
result2 = accuracy_score(y_test,ypred)
print('Accuracy:',result2)

Confusion Matrix:
[[37157     0    33     0     7]
 [    2     0     0     0     0]
 [  340     0     9     0     4]
 [   64     0     4     0     0]
 [  224     0    10     0     5]]
Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99     37197
           2       0.00      0.00      0.00         2
           3       0.16      0.03      0.04       353
           4       0.00      0.00      0.00        68
           6       0.31      0.02      0.04       239

    accuracy                           0.98     37859
   macro avg       0.29      0.21      0.21     37859
weighted avg       0.97      0.98      0.97     37859

Accuracy: 0.98182730658496


/Users/courtneycheung/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/courtneycheung/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/courtneycheung/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(r

### Approach 2: Naive Bayes
Naive Bayes assumes independence among features.

In [23]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train,y_train)
ypred=clf.predict(X_test)

In [24]:
result = confusion_matrix(y_test, ypred)
print('Confusion Matrix:')
print(result)
result1 = classification_report(y_test, ypred)
print('Classification Report:',)
print (result1)
result2 = accuracy_score(y_test,ypred)
print('Accuracy:',result2)

Confusion Matrix:
[[36163    14   907     0   113]
 [    1     0     1     0     0]
 [  169     0   170     0    14]
 [   42     0    22     0     4]
 [  127     0    87     0    25]]
Classification Report:
              precision    recall  f1-score   support

           0       0.99      0.97      0.98     37197
           2       0.00      0.00      0.00         2
           3       0.14      0.48      0.22       353
           4       0.00      0.00      0.00        68
           6       0.16      0.10      0.13       239

    accuracy                           0.96     37859
   macro avg       0.26      0.31      0.27     37859
weighted avg       0.98      0.96      0.97     37859

Accuracy: 0.9603528883488734


/Users/courtneycheung/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/courtneycheung/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/courtneycheung/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(r

### Approach 3: Ridge Regression Classifier
Regularization: penalization risk for complexity (goal: low MSE, small complexity)

In [25]:
from sklearn.linear_model import RidgeClassifier
clf = RidgeClassifier().fit(X_train,y_train)
ypred=clf.predict(X_test)

alpha = 1

In [26]:
result = confusion_matrix(y_test, ypred)
print('Confusion Matrix:')
print(result)
result1 = classification_report(y_test, ypred)
print('Classification Report:',)
print (result1)
result2 = accuracy_score(y_test,ypred)
print('Accuracy:',result2)

Confusion Matrix:
[[37197     0     0     0     0]
 [    2     0     0     0     0]
 [  353     0     0     0     0]
 [   68     0     0     0     0]
 [  239     0     0     0     0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99     37197
           2       0.00      0.00      0.00         2
           3       0.00      0.00      0.00       353
           4       0.00      0.00      0.00        68
           6       0.00      0.00      0.00       239

    accuracy                           0.98     37859
   macro avg       0.20      0.20      0.20     37859
weighted avg       0.97      0.98      0.97     37859

Accuracy: 0.9825140653477377


/Users/courtneycheung/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/courtneycheung/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/courtneycheung/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(r

### Approach 4: Random Forest

In [27]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(X_train,y_train)
ypred = clf.predict(X_test)

max depth = 2

In [28]:
result = confusion_matrix(y_test, ypred)
print('Confusion Matrix:')
print(result)
result1 = classification_report(y_test, ypred)
print('Classification Report:',)
print (result1)
result2 = accuracy_score(y_test,ypred)
print('Accuracy:',result2)

Confusion Matrix:
[[37197     0     0     0     0]
 [    2     0     0     0     0]
 [  353     0     0     0     0]
 [   68     0     0     0     0]
 [  239     0     0     0     0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99     37197
           2       0.00      0.00      0.00         2
           3       0.00      0.00      0.00       353
           4       0.00      0.00      0.00        68
           6       0.00      0.00      0.00       239

    accuracy                           0.98     37859
   macro avg       0.20      0.20      0.20     37859
weighted avg       0.97      0.98      0.97     37859

Accuracy: 0.9825140653477377


/Users/courtneycheung/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/courtneycheung/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/courtneycheung/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(r