In [1]:
from sklearn import preprocessing
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [24]:
df = pd.read_csv('data/new_health.csv')
df

Unnamed: 0  RELIG_SERVICES_12month  RELIG_IMPORTANT  \
0                0                     0.6         0.333333   
1                1                     0.4         0.666667   
2                2                     0.2         0.333333   
3                3                     0.6         0.000000   
4                4                     0.4         0.000000   
...            ...                     ...              ...   
189290      189290                     0.8         0.000000   
189291      189291                     0.4         1.000000   
189292      189292                     0.8         0.000000   
189293      189293                     0.6         0.333333   
189294      189294                     0.6         0.000000   

        RELIG_influ_decision  friend_SHARE_REL  Tabacco_Flag  Alcohol_Flag  \
0                   0.333333          0.333333           1.0           1.0   
1                   0.666667          1.000000           1.0           1.0   
2                   0.333333          0.666667           1.0           1.0   
3                   0.000000          0.333333           1.0           0.0   
4                   0.000000          0.333333           1.0           1.0   
...                      ...               ...           ...           ...   
189290              0.333333          0.666667           1.0           1.0   
189291              0.333333          0.666667           0.0           0.0   
189292              0.000000          0.666667           1.0           1.0   
189293              0.333333          1.000000           0.0           0.0   
189294              0.000000          0.000000           1.0           1.0   

        Marijunana_Flag  Marijuana_Only_Flag  Cocaine_Flag  ...  lifetime_mde  \
0                   1.0                  1.0           0.0  ...           1.0   
1                   1.0                  1.0           0.0  ...           1.0   
2                   0.0                  0.0           0.0  ...           0.0   
3                   0.0                  0.0           0.0  ...           1.0   
4                   1.0                  0.0           0.0  ...           0.0   
...                 ...                  ...           ...  ...           ...   
189290              0.0                  0.0           0.0  ...           1.0   
189291              0.0                  0.0           0.0  ...           0.0   
189292              1.0                  0.0           1.0  ...           1.0   
189293              0.0                  0.0           0.0  ...           0.0   
189294              1.0                  0.0           0.0  ...           1.0   

        pst_yr_mde   age  HEALTH  IRSEX   IRMARIT  EDUCCAT2  NEWRACE2  \
0              1.0  0.00    0.00    0.0  0.000000  0.666667  0.000000   
1              1.0  0.00    0.25    1.0  0.333333  0.666667  0.166667   
2              1.0  0.00    0.75    1.0  0.000000  0.000000  0.166667   
3              1.0  0.75    0.75    1.0  0.666667  0.333333  0.166667   
4              1.0  0.00    0.00    1.0  0.000000  0.666667  0.166667   
...            ...   ...     ...    ...       ...       ...       ...   
189290         1.0  0.00    0.00    1.0  0.000000  0.333333  0.166667   
189291         0.0  0.50    0.75    1.0  0.666667  0.333333  0.166667   
189292         1.0  0.50    0.25    0.0  0.333333  1.000000  0.166667   
189293         0.0  0.00    0.00    1.0  0.000000  0.666667  0.166667   
189294         1.0  1.00    0.75    0.0  0.333333  0.000000  0.333333   

        EMPSTATY  suicide_risk  
0       0.000000           0.0  
1       0.000000           0.0  
2       0.333333           0.0  
3       0.666667           0.0  
4       0.333333           0.0  
...          ...           ...  
189290  0.000000           0.0  
189291  0.333333           0.5  
189292  0.000000           0.0  
189293  1.000000           0.0  
189294  0.000000           0.0  

[189295 rows x 48 columns]

In [26]:
from sklearn.linear_model import Ridge
clf = Ridge().fit(X_train,y_train)
ypred=clf.predict(X_test)
# result = confusion_matrix(y_test, ypred)
# print('Confusion Matrix:')
# print(result)
# result1 = classification_report(y_test, ypred)
# print('Classification Report:',)
# print (result1)
# result2 = accuracy_score(y_test,ypred)
# print('Accuracy:',result2)

In [33]:
import numpy as np

In [34]:
np.where(clf.coef_ ==max(abs(clf.coef_)))

(array([34]),)

In [35]:
df.columns[34]

'suic_attempt'

In [30]:
max(abs(clf.coef_))

3.3171482848600804

In [3]:
#making suicide risk column categorical

In [4]:
df['suicide_risk'] = df['suicide_risk']*6
df = df.astype({'suicide_risk':'int'})

In [5]:
df

Unnamed: 0  RELIG_SERVICES_12month  RELIG_IMPORTANT  \
0                0                     0.6         0.333333   
1                1                     0.4         0.666667   
2                2                     0.2         0.333333   
3                3                     0.6         0.000000   
4                4                     0.4         0.000000   
...            ...                     ...              ...   
189290      189290                     0.8         0.000000   
189291      189291                     0.4         1.000000   
189292      189292                     0.8         0.000000   
189293      189293                     0.6         0.333333   
189294      189294                     0.6         0.000000   

        RELIG_influ_decision  friend_SHARE_REL  Tabacco_Flag  Alcohol_Flag  \
0                   0.333333          0.333333           1.0           1.0   
1                   0.666667          1.000000           1.0           1.0   
2                   0.333333          0.666667           1.0           1.0   
3                   0.000000          0.333333           1.0           0.0   
4                   0.000000          0.333333           1.0           1.0   
...                      ...               ...           ...           ...   
189290              0.333333          0.666667           1.0           1.0   
189291              0.333333          0.666667           0.0           0.0   
189292              0.000000          0.666667           1.0           1.0   
189293              0.333333          1.000000           0.0           0.0   
189294              0.000000          0.000000           1.0           1.0   

        Marijunana_Flag  Marijuana_Only_Flag  Cocaine_Flag  ...  lifetime_mde  \
0                   1.0                  1.0           0.0  ...           1.0   
1                   1.0                  1.0           0.0  ...           1.0   
2                   0.0                  0.0           0.0  ...           0.0   
3                   0.0                  0.0           0.0  ...           1.0   
4                   1.0                  0.0           0.0  ...           0.0   
...                 ...                  ...           ...  ...           ...   
189290              0.0                  0.0           0.0  ...           1.0   
189291              0.0                  0.0           0.0  ...           0.0   
189292              1.0                  0.0           1.0  ...           1.0   
189293              0.0                  0.0           0.0  ...           0.0   
189294              1.0                  0.0           0.0  ...           1.0   

        pst_yr_mde   age  HEALTH  IRSEX   IRMARIT  EDUCCAT2  NEWRACE2  \
0              1.0  0.00    0.00    0.0  0.000000  0.666667  0.000000   
1              1.0  0.00    0.25    1.0  0.333333  0.666667  0.166667   
2              1.0  0.00    0.75    1.0  0.000000  0.000000  0.166667   
3              1.0  0.75    0.75    1.0  0.666667  0.333333  0.166667   
4              1.0  0.00    0.00    1.0  0.000000  0.666667  0.166667   
...            ...   ...     ...    ...       ...       ...       ...   
189290         1.0  0.00    0.00    1.0  0.000000  0.333333  0.166667   
189291         0.0  0.50    0.75    1.0  0.666667  0.333333  0.166667   
189292         1.0  0.50    0.25    0.0  0.333333  1.000000  0.166667   
189293         0.0  0.00    0.00    1.0  0.000000  0.666667  0.166667   
189294         1.0  1.00    0.75    0.0  0.333333  0.000000  0.333333   

        EMPSTATY  suicide_risk  
0       0.000000             0  
1       0.000000             0  
2       0.333333             0  
3       0.666667             0  
4       0.333333             0  
...          ...           ...  
189290  0.000000             0  
189291  0.333333             3  
189292  0.000000             0  
189293  1.000000             0  
189294  0.000000             0  

[189295 rows x 48 columns]

In [6]:
df['suicide_risk'].value_counts()

0    185740
3      1896
6      1279
4       374
2         6
Name: suicide_risk, dtype: int64

### Suicide Risk

- plan1: think(1), plan(2), attempt(3) : doesn't work out, attempt doesn't ensure plan, and plan doesnt ensure thinking: for people who actually tried, half of them didn't have any plan, and some of them havent thought about killing themselves: something we could put into the slide as an interesting finding (might include some graphs as well)

- plan 2: think(1), think+plan(2), think+plan+attempt(3), but what about those who are attempt only, or plan only, or attempt+think?

- plan 3: think (+1), plan (+2), attempt (+3)


## K-Nearest Neighbors
K-Nearest Neighbors classifies based on proximity to k datapoints.

Note: There is a class imbalance. Since most people fall under the first risk category, K-NN is biased toward predicting that class. While it is good to have high accuracy, in the context of suicide risk, predicting 0 risk is not as important as predicting a risk of 2 or higher. 

Some disadvantages of K-NN observed here: doesn’t learn which features useful, computationally expensive, more noisy features → distance less meaningful

In [10]:
x_data = df.drop(['suicide_risk'],axis=1)
y_data = df['suicide_risk']

k = 5

In [11]:
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data,test_size=0.2, random_state = 1)

In [12]:
y_train.value_counts()

0    148543
3      1543
6      1040
4       306
2         4
Name: suicide_risk, dtype: int64

In [13]:
X_train, X_test, y_train, y_test = train_test_split(x_data, y_data,test_size=0.2, random_state = 1)
knn_clf=KNeighborsClassifier()
knn_clf.fit(X_train,y_train)
ypred=knn_clf.predict(X_test) #These are the predicted output values

In [14]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
result = confusion_matrix(y_test, ypred)
print('Confusion Matrix:')
print(result)
result1 = classification_report(y_test, ypred)
print('Classification Report:',)
print (result1)
result2 = accuracy_score(y_test,ypred)
print('Accuracy:',result2)

Confusion Matrix:
[[37196     0     1     0     0]
 [    2     0     0     0     0]
 [  353     0     0     0     0]
 [   68     0     0     0     0]
 [  239     0     0     0     0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99     37197
           2       0.00      0.00      0.00         2
           3       0.00      0.00      0.00       353
           4       0.00      0.00      0.00        68
           6       0.00      0.00      0.00       239

    accuracy                           0.98     37859
   macro avg       0.20      0.20      0.20     37859
weighted avg       0.97      0.98      0.97     37859

Accuracy: 0.9824876515491693


/Users/courtneycheung/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/courtneycheung/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/courtneycheung/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(r

## Naive Bayes
Naive Bayes assumes independence among features.

In [73]:
from sklearn.naive_bayes import MultinomialNB
clf = MultinomialNB()
clf.fit(X_train,y_train)
ypred=clf.predict(X_test)

In [74]:
ypred

array([0, 0, 0, ..., 0, 0, 0])

In [75]:
result = confusion_matrix(y_test, ypred)
print('Confusion Matrix:')
print(result)
result1 = classification_report(y_test, ypred)
print('Classification Report:',)
print (result1)
result2 = accuracy_score(y_test,ypred)
print('Accuracy:',result2)

Confusion Matrix:
[[36188   138   710    17   144]
 [    0     0     2     0     0]
 [    0     4   313     0    36]
 [    0     0     0    24    44]
 [    0     1     0     0   238]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.97      0.99     37197
           2       0.00      0.00      0.00         2
           3       0.31      0.89      0.45       353
           4       0.59      0.35      0.44        68
           6       0.52      1.00      0.68       239

    accuracy                           0.97     37859
   macro avg       0.48      0.64      0.51     37859
weighted avg       0.99      0.97      0.98     37859

Accuracy: 0.9710504767690642


ValueError: Classification metrics can't handle a mix of multiclass and continuous targets

## Ridge Regression
Regularization: penalization risk for complexity (goal: low MSE, small complexity)

In [16]:
from sklearn.linear_model import RidgeClassifier
clf = RidgeClassifier().fit(X_train,y_train)
ypred=clf.predict(X_test)

alpha = 1

In [17]:
result = confusion_matrix(y_test, ypred)
print('Confusion Matrix:')
print(result)
result1 = classification_report(y_test, ypred)
print('Classification Report:',)
print (result1)
result2 = accuracy_score(y_test,ypred)
print('Accuracy:',result2)

Confusion Matrix:
[[37197     0     0     0     0]
 [    0     0     2     0     0]
 [    0     0   353     0     0]
 [   68     0     0     0     0]
 [    0     0     0     0   239]]
Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     37197
           2       0.00      0.00      0.00         2
           3       0.99      1.00      1.00       353
           4       0.00      0.00      0.00        68
           6       1.00      1.00      1.00       239

    accuracy                           1.00     37859
   macro avg       0.60      0.60      0.60     37859
weighted avg       1.00      1.00      1.00     37859

Accuracy: 0.998151034100214


/Users/courtneycheung/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/courtneycheung/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/courtneycheung/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(r

In [18]:
clf.coef_

array([[ 1.04180276e-09,  1.93526789e-04,  2.11442991e-04,
        -2.26214316e-04,  9.18923067e-04, -5.88284156e-04,
         5.18310957e-04,  6.97421850e-04, -3.54851127e-04,
         1.07527541e-03,  1.29716789e-03,  1.21931621e-03,
        -9.88356456e-04, -1.17587932e-03,  6.32286002e-04,
         3.82159969e-04,  2.91294716e-04, -1.25451098e-03,
         1.99061972e-04, -5.50230777e-04, -1.95379654e-04,
        -9.67455168e-03,  1.03860053e-03, -3.02050582e-06,
        -1.45323390e-03, -1.64531399e-02,  1.92318106e-04,
         4.67863462e-04,  1.86248943e-03, -3.70534377e-02,
         1.62308039e-03,  4.70618198e-04, -6.84054100e-02,
        -1.66909621e+00, -6.40923272e-01, -4.02401790e-04,
        -9.59316709e-03,  9.20997022e-02, -4.62027433e-04,
         4.19576632e-04,  1.44235139e-03, -1.31798978e-03,
         3.10633812e-04, -2.57628974e-04,  1.09442677e-03,
        -1.77145745e-03,  8.25898904e-04],
       [ 5.28810319e-10, -1.26997495e-04,  2.23407876e-05,
        -8.36

## Random Forest

In [86]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(max_depth=2, random_state=0)
clf.fit(X_train,y_train)
ypred = clf.predict(X_test)

In [87]:
result = confusion_matrix(y_test, ypred)
print('Confusion Matrix:')
print(result)
result1 = classification_report(y_test, ypred)
print('Classification Report:',)
print (result1)
result2 = accuracy_score(y_test,ypred)
print('Accuracy:',result2)

Confusion Matrix:
[[37197     0     0     0     0]
 [    2     0     0     0     0]
 [  353     0     0     0     0]
 [   68     0     0     0     0]
 [  239     0     0     0     0]]
Classification Report:
              precision    recall  f1-score   support

           0       0.98      1.00      0.99     37197
           2       0.00      0.00      0.00         2
           3       0.00      0.00      0.00       353
           4       0.00      0.00      0.00        68
           6       0.00      0.00      0.00       239

    accuracy                           0.98     37859
   macro avg       0.20      0.20      0.20     37859
weighted avg       0.97      0.98      0.97     37859

Accuracy: 0.9825140653477377


/Users/courtneycheung/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/courtneycheung/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/Users/courtneycheung/opt/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(r