In [2]:
!pip install causal-learn

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 172 kB 12.7 MB/s eta 0:00:01
     |████████████████████████████████| 47 kB 13.4 MB/s eta 0:00:01


In [88]:
from causallearn.utils.cit import CIT
import pandas
from scipy.stats import chi2_contingency

import pandas as pd
import numpy as np

In [91]:
#read data
data_df = pd.read_csv('data/demo_religion_crime_health_2012.csv')
data_df.head()

Unnamed: 0  CASEID  inpatient  outpatient  needed_not_rcvd  rcvd_any_tmt  \
0           0       1        1.0         1.0              1.0           1.0   
1           1       2        1.0         1.0              1.0           1.0   
2           2       3        1.0         1.0              1.0           1.0   
3           3       4        1.0         1.0              1.0           1.0   
4           4       5        1.0         1.0              1.0           1.0   

   suic_thought_pst_12month  psych_distress_month  psych_distress_yr  \
0                       1.0                   0.0                0.0   
1                       1.0                   0.0                0.0   
2                       1.0                   0.0                0.0   
3                       1.0                   0.0                0.0   
4                       1.0                   0.0                0.0   

   suic_thought_pst_yr  ...       Health     Sex     Marriage  \
0                  0.0  ...  H_Excellent  Female  Not_Married   
1                  0.0  ...  H_Excellent  Female      Married   
2                  0.0  ...  H_Very_good    Male  Not_Married   
3                  0.0  ...  H_Very_good    Male  Not_Married   
4                  0.0  ...  H_Very_good    Male      Widowed   

              Education   Race    Employment  religion_services  \
0             Edu_youth  White  E_Unemployed                 99   
1          Some_college  White   E_full_time                1-2   
2  High_school_graduate  White   E_full_time                52+   
3          Some_college  White   E_part_time               6-24   
4      College_graduate  White   E_full_time                1-2   

  religion_important religion_influence_decision religion_share_important  
0                 99                          99                       99  
1              Agree                       Agree                 Disagree  
2     Strongly Agree              Strongly Agree                 Disagree  
3              Agree                       Agree        Strongly Disagree  
4  Strongly Disagree           Strongly Disagree        Strongly Disagree  

[5 rows x 32 columns]

In [69]:
# data_test = data_df[['inpatient', 'outpatient', 'rcvd_any_tmt']] 

In [92]:
def chisq_of_df_cols(df, c1, c2):
    groupsizes = df.groupby([c1, c2]).size()
    ctsum = groupsizes.unstack(c1)
    return chi2_contingency(ctsum.fillna(0))

Null hypothesis (H0): Variable 1 and variable 2 are not related in the population

p-value < 0.05: the null hypothesis is rejected and test is statistically significant 

In [93]:
chisq_of_df_cols(data_df, 'inpatient', 'rcvd_any_tmt')

(1591.0722769981255,
 0.0,
 1,
 array([[   80.37336252,  7894.62663748],
        [  476.62663748, 46816.37336252]]))

In [94]:
chisq_of_df_cols(data_df, 'outpatient', 'rcvd_any_tmt')

(11995.285918667014,
 0.0,
 1,
 array([[  583.82517913,  7391.17482087],
        [ 3462.17482087, 43830.82517913]]))

In [97]:
chisq_of_df_cols(data_df, 'suic_thought_pst_12month', 'psych_distress_yr')

(3348.2844173241488,
 0.0,
 1,
 array([[ 2623.44618948, 44360.55381052],
        [  462.55381052,  7821.44618948]]))

We can reject the null hypothesis under alpha=0.05 and therefore, we can speak about a statistically significant association between outpatient and inopatient treatment". 

**Importantly, association by itself does not imply causation. We need to distinguish between marginal associations and conditional associations. The latter is the key building block of causal inference.**
https://towardsdatascience.com/a-step-by-step-guide-in-detecting-causal-relationships-using-bayesian-structure-learning-in-python-c20c6b31cee5

## Causal-Learn 

data: numpy.ndarray, shape (n_samples, n_features). Data, where n_samples is the number of samples and n_features is the number of features.

In [28]:
chisq_obj = CIT(data, "chisq")

In [29]:
chisq_obj(X, Y, S)

NameError: name 'X' is not defined

In [30]:
from causallearn.search.ConstraintBased.PC import pc
from causallearn.utils.cit import chisq
cg = pc(data, 0.05, chisq)

AttributeError: 'list' object has no attribute 'shape'